name: build

on:
  push:
    branches: ["*"]

jobs:
  preprelease:
    name: Prepare Release
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'chore(release):')"

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}

      - name: Update Version
        id: version
        run: |
          previous=$(cat version.txt)
          version="$((previous + 1))"
          echo $version
          echo "$version" > version.txt
          echo "value=${version}" >> $GITHUB_OUTPUT

      - name: Preview Version
        run: echo ${{ steps.version.outputs.value }}

      - name: Commit Release
        run: |
          git diff
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "chore(release): prepare release for version ${{ steps.version.outputs.value }}"
          git push

      - name: Create Release
        id: createRelease
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.nextVersion.outputs.value }}
          name: Release v${{ steps.nextVersion.outputs.value }}
          token: ${{ secrets.GITHUB_TOKEN }}
