name: Publish Simulation

on:
  push:
    tags:
    - '[0-9]+' # tag pattern on pub.dev: 'v'

# Publish using custom workflow
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set Env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Simulate Release
        run: |
          echo "$RELEASE_VERSION"
          echo ${{ env.RELEASE_VERSION }}
